# Data analysis config

# TOML formatting, use literal strings surrounded by single quotes for strings. 
# TOML is intended to be obvious. Read about it at https://toml.io/en/

parent_folder = '/Users/nanostars/Desktop/2024 01 30'
# Where all temperature data is stored. 

output_path = '/Users/nanostars/Desktop/2024 01 30 analysis output'
# Where you would like to output the data.
# MUST NOT BE THE SAME AS parent_folder.

ft_file_pattern = '_table'
# feature table file pattern excluding the file-type 
# e.g. '_table'
# notice that .csv is excluded from the pattern

oi_file_pattern = '_Object Identities_{slice_index}'
# object identity image file pattern excluding the file type
# e.g. _Object Identites 
# notice that .tif is excluded from the pattern

method_vf = 'mode'
# method from which volume fractions for a single 
# capillary are assigned for use in, options are:
# 'mean', 'median', 'mode'

mode_bins = 100
# If using 'mode' for method_vf, how many bins are used in the 
# histogram for estimating the mode (tallest bin). 
# If not using 'mode' for method_vf, this parameter can be ignored. 

considered_capillaries = [1, 2, 3, 4, 5, 6, 7, 8, 9]
# List of capillariy #'s to consider for analysis.
# Say you want to exclude capillary 3 from the analysis, simply remove 3 from the list. 

[capillary_info]
capillary =     [    1,     2,     3,    4,     5,     6,     7,     8,    9]
concentration = [102.0,  66.0,   8.3, 48.4,  12.8,  73.4,  26.9, 115.8, 56.9]
melting_points = [37.75, 37.75, 36.75, 38.4, 37.35, 37.75, 37.75,  36.0, 37.5]
# Table containing capillaries corresponding with their concentrations and melting points. 
# Make sure that every value conatined in a single array is of the same type, i.e
#    an array of floats [1.43, 2.0, 1.99, 5.82]
#    an array of integers [1, 3, 9, 10]

[filter_criteria]
min_volume_fraction = 0
max_volume_fraction = 1
max_RMSE = 90
# Table containing filter criteria.

[figure_captions]
pd_x_label = '$\alpha_{\langle 3.5 \rangle}$'
pd_y_label = 'T ($^\circ$C)'
lr_x_label = '$\alpha_{\langle 3.5 \rangle}$'
lr_y_label = '$\phi_{\mathrm{den}}$'
# Table containing figure captions. 
# the "pd" prefix corresponds to "phase diagram"
# the "lr" prefix corresponds to "lever rule"
# latex formatting is allowed, use single "\"", don't worry about escape sequences.
# your backslash as an escape sequence