# Droplet fitting / computer vision config 

parent_folder = '/Users/nanostars/Desktop/2024 01 30'
# Where all temperature data is stored. 

a = 500
b = 20
c = 20
# a, b, c are labelling intensity parameters for the curve fit.
# They can be thought of as scaling prefactors that describe the intensity of:
# a - the background
# b - the dilute phase
# c - the dense phase
# b, and c should not be thought of as gray values, they are the amplitude, but a scaling factor.
# I typically set a = 500, b = 20, c = 20

epsilon = 0.5
# Bounds on the R_dil parameter of the 3D intensity fit are given by:
#   R_dil guess +/- epsilon    (in pixels)
# I typically set epsilon to 0.5 to allow the fit some freedom, but keep it restricted. 
# Using large epsilon can slow down the program and cause poor fits.

dense_radius_guess_type = 'area'
# How the dense phase radius parameter is guessed, options are:
#   'area' - use ilastik "object area" feature from training
#   'signal' - use radially averaged droplet intensity profile 