# ilastik training config

path_to_ilastik = '/Users/nanostars/ilastik-1.4.0.post1-OSX.app/Contents/ilastik-release/run_ilastik.sh'
# path to where ilastik is stored on the computer

parent_folder = '/Users/nanostars/Desktop/phase-diagrams/2024 01 24 a3_a4 1 to 1/Levers'
# path to parent folder containing all temperature subfolders

ilastik_project = '/Users/nanostars/Desktop/recognize_condensate.ilp'
# path to .ilp condensate recognition project

file_extension = 'tif'
# file extension of both input and output images

export_source = 'object identities'
# export image source option in ilastik
